name: Cypress Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}
          CYPRESS_test_email: ${{ secrets.CYPRESS_TEST_EMAIL }}
          CYPRESS_test_password: ${{ secrets.CYPRESS_TEST_PASSWORD }}
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-snapshots
            path: cypress/screenshots/sign_in.cy.ts
